version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-13.29
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - cache-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack --no-terminal setup
      - run:
          name: Run tests
          command: stack --no-terminal test
      - save_cache:
          name: Cache Dependencies
          key: cache-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
